package Clases;
// Generated 21-Jun-2013 10:00:31 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import logica.EstudianteLogic;

/**
 * CalificacionEstudiante generated by hbm2java
 */
public class CalificacionEstudiante  implements java.io.Serializable {


     private int regestId;
     private Estudiante estudiante;
     private Parcial parcial;
     private CursoMateria cursoMateria;
     private Date calestFecha;
     private Double calestNota;

    public CalificacionEstudiante() {
    }

	
    public CalificacionEstudiante(int regestId, Estudiante estudiante, Parcial parcial, CursoMateria cursoMateria) {
        this.regestId = regestId;
        this.estudiante = estudiante;
        this.parcial = parcial;
        this.cursoMateria = cursoMateria;
    }
    public CalificacionEstudiante(int regestId, Estudiante estudiante, Parcial parcial, CursoMateria cursoMateria, Date calestFecha, Double calestNota) {
       this.regestId = regestId;
       this.estudiante = estudiante;
       this.parcial = parcial;
       this.cursoMateria = cursoMateria;
       this.calestFecha = calestFecha;
       this.calestNota = calestNota;
    }
   
    public int getRegestId() {
        return this.regestId;
    }
    
    public void setRegestId(int regestId) {
        this.regestId = regestId;
    }
    public Estudiante getEstudiante() {
        EstudianteLogic el = new EstudianteLogic();
        return el.obtenerUnico(""+estudiante.getPerId());
        //return this.estudiante;
    }
    
    public void setEstudiante(Estudiante estudiante) {
        this.estudiante = estudiante;
    }
    public Parcial getParcial() {
        return this.parcial;
    }
    
    public void setParcial(Parcial parcial) {
        this.parcial = parcial;
    }
    public CursoMateria getCursoMateria() {
        return this.cursoMateria;
    }
    
    public void setCursoMateria(CursoMateria cursoMateria) {
        this.cursoMateria = cursoMateria;
    }
    public Date getCalestFecha() {
        return this.calestFecha;
    }
    
    public void setCalestFecha(Date calestFecha) {
        this.calestFecha = calestFecha;
    }
    public Double getCalestNota() {
        return this.calestNota;
    }
    
    public void setCalestNota(Double calestNota) {
        this.calestNota = calestNota;
    }




}


