package Clases;
// Generated 21-Jun-2013 10:00:31 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import logica.MateriaLogic;
import logica.ProfesorLogic;

/**
 * CursoMateria generated by hbm2java
 */
public class CursoMateria  implements java.io.Serializable {


     private int curmatId;
     private Profesor profesor;
     private Materia materia;
     private Curso curso;
     private Set<CalificacionEstudiante> calificacionEstudiantes = new HashSet<CalificacionEstudiante>(0);

    public CursoMateria() {
    }

	
    public CursoMateria(int curmatId, Profesor profesor, Materia materia, Curso curso) {
        this.curmatId = curmatId;
        this.profesor = profesor;
        this.materia = materia;
        this.curso = curso;
    }
    public CursoMateria(int curmatId, Profesor profesor, Materia materia, Curso curso, Set<CalificacionEstudiante> calificacionEstudiantes) {
       this.curmatId = curmatId;
       this.profesor = profesor;
       this.materia = materia;
       this.curso = curso;
       this.calificacionEstudiantes = calificacionEstudiantes;
    }
   
    public int getCurmatId() {
        return this.curmatId;
    }
    
    public void setCurmatId(int curmatId) {
        this.curmatId = curmatId;
    }
    public Profesor getProfesor() {
        ProfesorLogic pl = new ProfesorLogic();
        return pl.obtenerUnico(""+this.profesor.getPerId());
        //return this.profesor;
    }
    
    public void setProfesor(Profesor profesor) {
        this.profesor = profesor;
    }
    public Materia getMateria() {
        MateriaLogic ml = new MateriaLogic();
        return ml.buscarUnica(""+this.materia.getMatId());
        //return this.materia;
    }
    
    public void setMateria(Materia materia) {
        this.materia = materia;
    }
    public Curso getCurso() {
        return this.curso;
    }
    
    public void setCurso(Curso curso) {
        this.curso = curso;
    }
    public Set<CalificacionEstudiante> getCalificacionEstudiantes() {
        return this.calificacionEstudiantes;
    }
    
    public void setCalificacionEstudiantes(Set<CalificacionEstudiante> calificacionEstudiantes) {
        this.calificacionEstudiantes = calificacionEstudiantes;
    }




}


