package Clases;
// Generated 21-Jun-2013 10:00:31 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Materia generated by hbm2java
 */
public class Materia  implements java.io.Serializable {


     private int matId;
     private Estado estado;
     private Integer matEstado;
     private String matNombre;
     private Set<CursoMateria> cursoMaterias = new HashSet<CursoMateria>(0);

    public Materia() {
    }

	
    public Materia(int matId, String matNombre) {
        this.matId = matId;
        this.matNombre = matNombre;
    }
    public Materia(int matId, Estado estado, Integer matEstado, String matNombre, Set<CursoMateria> cursoMaterias) {
       this.matId = matId;
       this.estado = estado;
       this.matEstado = matEstado;
       this.matNombre = matNombre;
       this.cursoMaterias = cursoMaterias;
    }
   
    public int getMatId() {
        return this.matId;
    }
    
    public void setMatId(int matId) {
        this.matId = matId;
    }
    public Estado getEstado() {
        return this.estado;
    }
    
    public void setEstado(Estado estado) {
        this.estado = estado;
    }
    public Integer getMatEstado() {
        return this.matEstado;
    }
    
    public void setMatEstado(Integer matEstado) {
        this.matEstado = matEstado;
    }
    public String getMatNombre() {
        return this.matNombre;
    }
    
    public void setMatNombre(String matNombre) {
        this.matNombre = matNombre;
    }
    public Set<CursoMateria> getCursoMaterias() {
        return this.cursoMaterias;
    }
    
    public void setCursoMaterias(Set<CursoMateria> cursoMaterias) {
        this.cursoMaterias = cursoMaterias;
    }




}


