package Clases;
// Generated 21-Jun-2013 10:00:31 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Parentezco generated by hbm2java
 */
public class Parentesco  implements java.io.Serializable {


     private int parId;
     private String parentTipo;
     private Set<PadreFamilia> padreFamilias = new HashSet<PadreFamilia>(0);

    public Parentesco() {
    }

	
    public Parentesco(int parId) {
        this.parId = parId;
    }
    public Parentesco(int parId, String parentTipo, Set<PadreFamilia> padreFamilias) {
       this.parId = parId;
       this.parentTipo = parentTipo;
       this.padreFamilias = padreFamilias;
    }
   
    public int getParId() {
        return this.parId;
    }
    
    public void setParId(int parId) {
        this.parId = parId;
    }
    public String getParentTipo() {
        return this.parentTipo;
    }
    
    public void setParentTipo(String parentTipo) {
        this.parentTipo = parentTipo;
    }
    public Set<PadreFamilia> getPadreFamilias() {
        return this.padreFamilias;
    }
    
    public void setPadreFamilias(Set<PadreFamilia> padreFamilias) {
        this.padreFamilias = padreFamilias;
    }




}


