package Clases;
// Generated 21-Jun-2013 10:00:31 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Periodo generated by hbm2java
 */
public class Periodo  implements java.io.Serializable {


     private int perId;
     private Integer perAnioLectivo;
     private String perDescripcion;
     private Set<Parcial> parcials = new HashSet<Parcial>(0);

    public Periodo() {
    }

	
    public Periodo(int perId) {
        this.perId = perId;
    }
    public Periodo(int perId, Integer perAnioLectivo, String perDescripcion, Set<Parcial> parcials) {
       this.perId = perId;
       this.perAnioLectivo = perAnioLectivo;
       this.perDescripcion = perDescripcion;
       this.parcials = parcials;
    }
   
    public int getPerId() {
        return this.perId;
    }
    
    public void setPerId(int perId) {
        this.perId = perId;
    }
    public Integer getPerAnioLectivo() {
        return this.perAnioLectivo;
    }
    
    public void setPerAnioLectivo(Integer perAnioLectivo) {
        this.perAnioLectivo = perAnioLectivo;
    }
    public String getPerDescripcion() {
        return this.perDescripcion;
    }
    
    public void setPerDescripcion(String perDescripcion) {
        this.perDescripcion = perDescripcion;
    }
    public Set<Parcial> getParcials() {
        return this.parcials;
    }
    
    public void setParcials(Set<Parcial> parcials) {
        this.parcials = parcials;
    }




}


