package Clases;
// Generated 21-Jun-2013 10:00:31 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Seccion generated by hbm2java
 */
public class Seccion  implements java.io.Serializable {


     private int secId;
     private Integer secAnioLectivo;
     private String secNombre;
     private Integer secInicio;
     private Integer secFin;
     private Set<Curso> cursos = new HashSet<Curso>(0);

    public Seccion() {
    }

	
    public Seccion(int secId) {
        this.secId = secId;
    }
    public Seccion(int secId, Integer secAnioLectivo, String secNombre, Integer secInicio, Integer secFin, Set<Curso> cursos) {
       this.secId = secId;
       this.secAnioLectivo = secAnioLectivo;
       this.secNombre = secNombre;
       this.secInicio = secInicio;
       this.secFin = secFin;
       this.cursos = cursos;
    }
   
    public int getSecId() {
        return this.secId;
    }
    
    public void setSecId(int secId) {
        this.secId = secId;
    }
    public Integer getSecAnioLectivo() {
        return this.secAnioLectivo;
    }
    
    public void setSecAnioLectivo(Integer secAnioLectivo) {
        this.secAnioLectivo = secAnioLectivo;
    }
    public String getSecNombre() {
        return this.secNombre;
    }
    
    public void setSecNombre(String secNombre) {
        this.secNombre = secNombre;
    }
    public Integer getSecInicio() {
        return this.secInicio;
    }
    
    public void setSecInicio(Integer secInicio) {
        this.secInicio = secInicio;
    }
    public Integer getSecFin() {
        return this.secFin;
    }
    
    public void setSecFin(Integer secFin) {
        this.secFin = secFin;
    }
    public Set<Curso> getCursos() {
        return this.cursos;
    }
    
    public void setCursos(Set<Curso> cursos) {
        this.cursos = cursos;
    }




}


