package Clases;
// Generated 21-Jun-2013 10:00:31 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import logica.PersonaLogic;

/**
 * Estudiante generated by hbm2java
 */
public class Estudiante  implements java.io.Serializable {


     private int perId;
     private Persona persona;
     private Estado estado;
     private Date estFechaIngreso;
     private Set<CursoEstudiante> cursoEstudiantes = new HashSet<CursoEstudiante>(0);
     private Set<CalificacionEstudiante> calificacionEstudiantes = new HashSet<CalificacionEstudiante>(0);

    public Estudiante() {
    }

	
    public Estudiante(int perId, Persona persona) {
        this.perId = perId;
        this.persona = persona;
    }

    public Estudiante(int perId) {
        this.perId = perId;
    }
    
    
    public Estudiante(int perId, Persona persona, Estado estado, Date estFechaIngreso, Set<CursoEstudiante> cursoEstudiantes, Set<CalificacionEstudiante> calificacionEstudiantes) {
       this.perId = perId;
       this.persona = persona;
       this.estado = estado;
       this.estFechaIngreso = estFechaIngreso;
       this.cursoEstudiantes = cursoEstudiantes;
       this.calificacionEstudiantes = calificacionEstudiantes;
    }
   
    public int getPerId() {
        return this.perId;
    }
    
    public void setPerId(int perId) {
        this.perId = perId;
    }
    public Persona getPersona() {
        PersonaLogic pl = new PersonaLogic();
        return pl.buscarUnica(""+perId);
        //return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Estado getEstado() {
        return this.estado;
    }
    
    public void setEstado(Estado estado) {
        this.estado = estado;
    }
    public Date getEstFechaIngreso() {
        return this.estFechaIngreso;
    }
    
    public void setEstFechaIngreso(Date estFechaIngreso) {
        this.estFechaIngreso = estFechaIngreso;
    }
    public Set<CursoEstudiante> getCursoEstudiantes() {
        return this.cursoEstudiantes;
    }
    
    public void setCursoEstudiantes(Set<CursoEstudiante> cursoEstudiantes) {
        this.cursoEstudiantes = cursoEstudiantes;
    }
    public Set<CalificacionEstudiante> getCalificacionEstudiantes() {
        return this.calificacionEstudiantes;
    }
    
    public void setCalificacionEstudiantes(Set<CalificacionEstudiante> calificacionEstudiantes) {
        this.calificacionEstudiantes = calificacionEstudiantes;
    }




}


