package Clases;
// Generated 21-Jun-2013 10:00:31 by Hibernate Tools 3.2.1.GA



/**
 * PadreFamilia generated by hbm2java
 */
public class PadreFamilia  implements java.io.Serializable {


     private int familiar;
     private Persona personaByEstudiante;
     private Parentesco parentesco;
     private Persona personaByFamiliar;
     private boolean representante;

    public PadreFamilia() {
    }

	
    public PadreFamilia(int familiar, Parentesco parentesco, Persona personaByFamiliar, boolean representante) {
        this.familiar = familiar;
        this.parentesco = parentesco;
        this.personaByFamiliar = personaByFamiliar;
        this.representante = representante;
    }
    public PadreFamilia(int familiar, Persona personaByEstudiante, Parentesco parentesco, Persona personaByFamiliar, boolean representante) {
       this.familiar = familiar;
       this.personaByEstudiante = personaByEstudiante;
       this.parentesco = parentesco;
       this.personaByFamiliar = personaByFamiliar;
       this.representante = representante;
    }
   
    public int getFamiliar() {
        return this.familiar;
    }
    
    public void setFamiliar(int familiar) {
        this.familiar = familiar;
    }
    public Persona getPersonaByEstudiante() {
        return this.personaByEstudiante;
    }
    
    public void setPersonaByEstudiante(Persona personaByEstudiante) {
        this.personaByEstudiante = personaByEstudiante;
    }
    public Parentesco getParentesco() {
        return this.parentesco;
    }
    
    public void setParentesco(Parentesco parentesco) {
        this.parentesco = parentesco;
    }
    public Persona getPersonaByFamiliar() {
        return this.personaByFamiliar;
    }
    
    public void setPersonaByFamiliar(Persona personaByFamiliar) {
        this.personaByFamiliar = personaByFamiliar;
    }
    public boolean isRepresentante() {
        return this.representante;
    }
    
    public void setRepresentante(boolean representante) {
        this.representante = representante;
    }




}


