package Clases;
// Generated 21-Jun-2013 10:00:31 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Parcial generated by hbm2java
 */
public class Parcial  implements java.io.Serializable {


     private int parcId;
     private Periodo periodo;
     private Date parcFechaaInicio;
     private Date parcFechaFin;
     private String parcDescripcion;
     private Double parcPorcentaje;
     private Set<CalificacionEstudiante> calificacionEstudiantes = new HashSet<CalificacionEstudiante>(0);

    public Parcial() {
    }

	
    public Parcial(int parcId, Periodo periodo, Date parcFechaFin) {
        this.parcId = parcId;
        this.periodo = periodo;
        this.parcFechaFin = parcFechaFin;
    }
    public Parcial(int parcId, Periodo periodo, Date parcFechaaInicio, Date parcFechaFin, String parcDescripcion, Double parcPorcentaje, Set<CalificacionEstudiante> calificacionEstudiantes) {
       this.parcId = parcId;
       this.periodo = periodo;
       this.parcFechaaInicio = parcFechaaInicio;
       this.parcFechaFin = parcFechaFin;
       this.parcDescripcion = parcDescripcion;
       this.parcPorcentaje = parcPorcentaje;
       this.calificacionEstudiantes = calificacionEstudiantes;
    }
   
    public int getParcId() {
        return this.parcId;
    }
    
    public void setParcId(int parcId) {
        this.parcId = parcId;
    }
    public Periodo getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(Periodo periodo) {
        this.periodo = periodo;
    }
    public Date getParcFechaaInicio() {
        return this.parcFechaaInicio;
    }
    
    public void setParcFechaaInicio(Date parcFechaaInicio) {
        this.parcFechaaInicio = parcFechaaInicio;
    }
    public Date getParcFechaFin() {
        return this.parcFechaFin;
    }
    
    public void setParcFechaFin(Date parcFechaFin) {
        this.parcFechaFin = parcFechaFin;
    }
    public String getParcDescripcion() {
        return this.parcDescripcion;
    }
    
    public void setParcDescripcion(String parcDescripcion) {
        this.parcDescripcion = parcDescripcion;
    }
    public Double getParcPorcentaje() {
        return this.parcPorcentaje;
    }
    
    public void setParcPorcentaje(Double parcPorcentaje) {
        this.parcPorcentaje = parcPorcentaje;
    }
    public Set<CalificacionEstudiante> getCalificacionEstudiantes() {
        return this.calificacionEstudiantes;
    }
    
    public void setCalificacionEstudiantes(Set<CalificacionEstudiante> calificacionEstudiantes) {
        this.calificacionEstudiantes = calificacionEstudiantes;
    }




}


