package Clases;
// Generated 21-Jun-2013 10:00:31 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Profesor generated by hbm2java
 */
public class Profesor  implements java.io.Serializable {


     private int perId;
     private Persona persona;
     private Estado estado;
     private String profTitulo;
     private String profFechaIngreso;
     private Set<CursoMateria> cursoMaterias = new HashSet<CursoMateria>(0);

    public Profesor() {
    }

	
    public Profesor(int perId, Persona persona) {
        this.perId = perId;
        this.persona = persona;
    }
    public Profesor(int perId, Persona persona, Estado estado, String profTitulo, String profFechaIngreso, Set<CursoMateria> cursoMaterias) {
       this.perId = perId;
       this.persona = persona;
       this.estado = estado;
       this.profTitulo = profTitulo;
       this.profFechaIngreso = profFechaIngreso;
       this.cursoMaterias = cursoMaterias;
    }
   
    public int getPerId() {
        return this.perId;
    }
    
    public void setPerId(int perId) {
        this.perId = perId;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Estado getEstado() {
        return this.estado;
    }
    
    public void setEstado(Estado estado) {
        this.estado = estado;
    }
    public String getProfTitulo() {
        return this.profTitulo;
    }
    
    public void setProfTitulo(String profTitulo) {
        this.profTitulo = profTitulo;
    }
    public String getProfFechaIngreso() {
        return this.profFechaIngreso;
    }
    
    public void setProfFechaIngreso(String profFechaIngreso) {
        this.profFechaIngreso = profFechaIngreso;
    }
    public Set<CursoMateria> getCursoMaterias() {
        return this.cursoMaterias;
    }
    
    public void setCursoMaterias(Set<CursoMateria> cursoMaterias) {
        this.cursoMaterias = cursoMaterias;
    }




}


